include: package:flutter_lints/flutter.yaml
linter:
  rules:
    avoid_shadowing_type_parameters: false
    prefer_const_constructors: false
    non_constant_identifier_names: false
    prefer_const_literals_to_create_immutables: false
    use_build_context_synchronously: false
    camel_case_types: false
    file_names: false
    prefer_typing_uninitialized_variables: false
    avoid_print: false
    depend_on_referenced_packages: false
    library_private_types_in_public_api: false